In [1]:
tauRefs = [10 ** round((i / 20), 2) for i in range(49, 61)]

In [2]:
tauRefs

[281.8382931264455,
 316.22776601683796,
 354.8133892335753,
 398.1071705534973,
 446.683592150963,
 501.18723362727246,
 562.341325190349,
 630.957344480193,
 707.945784384138,
 794.3282347242813,
 891.2509381337459,
 1000.0]

In [3]:
[10 ** (i / 10) for i in range(49, 61)]

[79432.82347242821,
 100000.0,
 125892.54117941661,
 158489.3192461114,
 199526.2314968879,
 251188.6431509582,
 316227.7660168379,
 398107.1705534969,
 501187.2336272725,
 630957.344480193,
 794328.2347242822,
 1000000.0]

In [7]:
ravel

NameError: name 'ravel' is not defined

In [10]:
from functools import reduce

In [11]:
import numpy as np

In [14]:
np.arange(10, 20, 0.1)

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9])

In [ ]:
reduce()

In [ ]:
[]

In [19]:
exps = 

In [21]:
len(exps)

21

In [22]:
exps

array([5.  , 5.05, 5.1 , 5.15, 5.2 , 5.25, 5.3 , 5.35, 5.4 , 5.45, 5.5 ,
       5.55, 5.6 , 5.65, 5.7 , 5.75, 5.8 , 5.85, 5.9 , 5.95, 6.  ])

In [60]:
tauRefs = [10. ** i for i in np.arange(5, 6.05, 0.05)]

In [61]:
tauRefs

[100000.0,
 112201.84543019629,
 125892.54117941661,
 141253.75446227525,
 158489.3192461111,
 177827.94100389193,
 199526.23149688746,
 223872.1138568333,
 251188.64315095718,
 281838.29312644433,
 316227.7660168366,
 354813.38923357386,
 398107.1705534953,
 446683.59215096076,
 501187.2336272694,
 562341.3251903456,
 630957.3444801891,
 707945.784384133,
 794328.2347242757,
 891250.9381337386,
 999999.9999999919]

In [62]:
len(tauRefs)

21

[0.707, 1.0, 1.414]

In [66]:
import itertools

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [73]:
geometry = 

In [74]:
len(geometry)

12

In [76]:
geometry

[(0.5, 1.0),
 (0.5, 1.414),
 (0.6, 1.0),
 (0.6, 1.414),
 (0.7, 1.0),
 (0.7, 1.414),
 (0.8, 1.0),
 (0.8, 1.414),
 (0.9, 1.0),
 (0.9, 1.414),
 (1.0, 1.0),
 (1.0, 1.414)]

In [86]:
tauRefFreqs = 

In [ ]:
geometry = 

In [88]:
list(itertools.product(
    [0.5, 1.0],
    [1.,],
    ))

[(0.5, 1.0), (1.0, 1.0)]

In [89]:
list(itertools.product(
    [10 ** i for i in np.linspace(5, 6, 6)],
    [1.,],
    [0.5, 1.0],
    [1.,],
    ))

[(100000.0, 1.0, 0.5, 1.0),
 (100000.0, 1.0, 1.0, 1.0),
 (158489.3192461114, 1.0, 0.5, 1.0),
 (158489.3192461114, 1.0, 1.0, 1.0),
 (251188.6431509582, 1.0, 0.5, 1.0),
 (251188.6431509582, 1.0, 1.0, 1.0),
 (398107.1705534969, 1.0, 0.5, 1.0),
 (398107.1705534969, 1.0, 1.0, 1.0),
 (630957.344480193, 1.0, 0.5, 1.0),
 (630957.344480193, 1.0, 1.0, 1.0),
 (1000000.0, 1.0, 0.5, 1.0),
 (1000000.0, 1.0, 1.0, 1.0)]