In [1]:
import numpy as np

In [97]:
np.linspace(4.9, 6.05, 24)

array([4.9 , 4.95, 5.  , 5.05, 5.1 , 5.15, 5.2 , 5.25, 5.3 , 5.35, 5.4 ,
       5.45, 5.5 , 5.55, 5.6 , 5.65, 5.7 , 5.75, 5.8 , 5.85, 5.9 , 5.95,
       6.  , 6.05])

In [99]:
np.linspace(5.9, 6.05, 4)

array([5.9 , 5.95, 6.  , 6.05])

In [92]:
ARG1, ARG2 = 1, 2
(10. ** (np.linspace(5.3, 5.85, 12), np.linspace(5.5, 6.05, 12))[ARG1])[ARG2]

398107.1705534969

In [82]:
5.3 in np.linspace(5.3, 5.85, 12)

True

In [87]:
np.linspace(4.9, 6.05, 24)

array([4.9 , 4.95, 5.  , 5.05, 5.1 , 5.15, 5.2 , 5.25, 5.3 , 5.35, 5.4 ,
       5.45, 5.5 , 5.55, 5.6 , 5.65, 5.7 , 5.75, 5.8 , 5.85, 5.9 , 5.95,
       6.  , 6.05])

In [ ]:
v for v in np.linspace(4.95)

In [74]:
fs = [float(v) for v in [*np.linspace(0.72, 0.78, 4), *np.linspace(0.55, 0.95, 5)]]

In [80]:
np.linspace(5.5, 6.05, 12)

array([5.5 , 5.55, 5.6 , 5.65, 5.7 , 5.75, 5.8 , 5.85, 5.9 , 5.95, 6.  ,
       6.05])

In [ ]:
np.linspace(5.3, 5.85, 12)

In [75]:
fs

[0.72, 0.74, 0.76, 0.78, 0.55, 0.65, 0.75, 0.85, 0.95]

In [76]:
len(fs)

9

In [60]:
np.linspace(0.72, 0.78, 4)

array([0.72, 0.74, 0.76, 0.78])

In [43]:
aspects = [float(i) for i in np.round(2. ** np.linspace(0, 0.5, 11), 3)][1:-1]

In [53]:
len(aspects)

9

In [ ]:
inputs['aspect'] = round((2. ** np.linspace(0, 0.5, 6)[1:-1])[ARG2], 3)
inputs['aspect'] = [1.072, 1.149, 1.231, 1.32][ARG2]

In [12]:
np.round((2. ** np.linspace(0, 0.5, 12))[1:-1], 3)

array([1.032, 1.065, 1.099, 1.134, 1.171, 1.208, 1.247, 1.287, 1.328,
       1.37 ])

In [15]:
aspect = [1.032, 1.065, 1.099, 1.134, 1.171, 1.208, 1.247, 1.287, 1.328, 1.37]

In [16]:
aspect

[1.032, 1.065, 1.099, 1.134, 1.171, 1.208, 1.247, 1.287, 1.328, 1.37]

In [17]:
len(aspect)

10

In [ ]:
[1.072, 1.149, 1.231, 1.32]

In [50]:
aspects

[1.035, 1.072, 1.11, 1.149, 1.189, 1.231, 1.275, 1.32, 1.366]

In [51]:
args = [0, 2, 4, 6, 8]

In [52]:
[aspects[i] for i in args]

[1.035, 1.11, 1.189, 1.275, 1.366]

In [11]:
np.round

<function numpy.round_(a, decimals=0, out=None)>

In [2]:
np.linspace(5.3, 5.85, 12)

array([5.3 , 5.35, 5.4 , 5.45, 5.5 , 5.55, 5.6 , 5.65, 5.7 , 5.75, 5.8 ,
       5.85])

In [5]:
[*np.linspace(4.95, 5.25, 6),]

[4.95, 5.01, 5.07, 5.13, 5.19, 5.25]

In [6]:
np.linspace(5.9, 5.2, 6)

array([5.9 , 5.76, 5.62, 5.48, 5.34, 5.2 ])

In [ ]:
np.linspace(5.3, 5.85, 12)

In [ ]:
tauRefs = 10. ** np.linspace(5.3, 5.85, 12)

In [ ]:
tauRefs[0]

In [ ]:
np.log10(tauRefs[0])

In [ ]:
np.linspace(0.72, 0.78, 4)

In [ ]:
2. ** np.linspace(-0.5, 0.5, 5)

In [ ]:
2. ** np.linspace(0, 0.5, 6)[1:-1]

In [ ]:
ARG2 = 2

In [ ]:
round((2. ** np.linspace(0, 0.5, 6)[1:-1])[ARG2], 3)

In [ ]:
for ARG2 in range(4):
    print(round((2. ** np.linspace(0, 0.5, 6)[1:-1])[ARG2], 3))

In [ ]:
ARG2 = 0
[round((2. ** np.linspace(0, 0.5, 6)[1:-1])[i], 3) for i in range(4)]

In [ ]:
round(64 * 1.32)

In [ ]:
np.linspace(0., 1., round(64 * 1.072))